import React from 'react'
import type { Metadata } from 'next'
import './css/globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import ServiceWorkerRegister from '@/app/components/service-worker/ServiceWorkerRegister'
import { RestaurantProvider } from '@/context/RestaurantContext'

export const metadata: Metadata = {
  title: 'TailwindAdmin - Nextjs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {  
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='icon' href='/favicon.svg' type='image/svg+xml' />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#5d87ff" />
      </head>
      <body className='antialiased'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <RestaurantProvider>
            <ServiceWorkerRegister />
            {children}
          </RestaurantProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
